# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'podForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1366, 768)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(500, 60, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(280, 590, 161, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Frame)
        self.pushButton_2.setGeometry(QtCore.QRect(910, 590, 161, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(60, 250, 771, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(1090, 240, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(Frame)
        self.label_5.setGeometry(QtCore.QRect(60, 200, 771, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit1 = QtWidgets.QLineEdit(Frame)
        self.lineEdit1.setGeometry(QtCore.QRect(1090, 190, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit1.setFont(font)
        self.lineEdit1.setText("")
        self.lineEdit1.setObjectName("lineEdit1")
        self.label_6 = QtWidgets.QLabel(Frame)
        self.label_6.setGeometry(QtCore.QRect(60, 300, 991, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(1090, 310, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(Frame)
        self.label_7.setGeometry(QtCore.QRect(60, 380, 991, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(1090, 380, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "Податкова форма. Для III групи 2%"))
        self.pushButton.setText(_translate("Frame", "Назад"))
        self.pushButton_2.setText(_translate("Frame", "Відправити"))
        self.label_4.setText(_translate("Frame", "Обсяг доходу за податковий (звітний) місяць, що оподатковується за ставкою 2 відсотки доходу:"))
        self.label_5.setText(_translate("Frame", "Податковий (звітний) період, який уточнюється:"))
        self.label_6.setText(_translate("Frame", "Позитивне значення різниці між сумою загального мінімального\n"
"податкового зобов’язання та загальною сумою сплачених податків, зборів, платежів та витрат на оренду земельних ділянок:"))
        self.label_7.setText(_translate("Frame", "Уточнена сума податкових зобов’язань за податковий (звітний) період, у якому виявлена помилка:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
